spring:
  mail:
    host: smtp.gmail.com
    username: educationalpurpose076@gmail.com
    password: qwertyuiop1234567890!@#$%^&*()
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

#1. turn on Allow less secure apps in settings
# 2. go to https://accounts.google.com/DisplayUnlockCaptcha and click continue